"""Added SiteSetting and Media models

Revision ID: 03254202c6f2
Revises: d12cd0dea5b4
Create Date: 2026-08-06 05:08:52.213560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03254202c6f2'
down_revision: Union[str, Sequence[str], None] = 'd12cd0dea5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
