"""Added SiteSetting and Media models

Revision ID: 04c6e4e8ad07
Revises: d57e76a56aad
Create Date: 2026-08-08 00:53:48.424470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c6e4e8ad07'
down_revision: Union[str, Sequence[str], None] = 'd57e76a56aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
