"""add is_published to content_blocks

Revision ID: c4ac3ebd01a3
Revises: d88eb3b32399
Create Date: 2026-07-21 05:43:15.997943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ac3ebd01a3'
down_revision: Union[str, Sequence[str], None] = 'd88eb3b32399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_blocks', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.execute("ALTER TABLE messages ALTER COLUMN services TYPE servicetype USING services::servicetype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'services',
               existing_type=sa.Enum('web_development', 'seo', 'graphic_design', 'digital_marketing', 'app_development', 'content_writing', 'other', name='servicetype'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('content_blocks', 'is_published')
    # ### end Alembic commands ###
    
    

    

