"""Added SiteSetting and Media models

Revision ID: d12cd0dea5b4
Revises: 93ab0b40a264
Create Date: 2026-07-22 05:42:28.555760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12cd0dea5b4'
down_revision: Union[str, Sequence[str], None] = '93ab0b40a264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
