"""Added SiteSetting and Media models

Revision ID: d57e76a56aad
Revises: d5aef9d9d1ed
Create Date: 2026-08-06 23:39:46.975833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57e76a56aad'
down_revision: Union[str, Sequence[str], None] = 'd5aef9d9d1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'name')
    # ### end Alembic commands ###
