"""rename subject to services in messages

Revision ID: d88eb3b32399
Revises: ccd4c83d1f4e
Create Date: 2026-07-21 05:08:52.214561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88eb3b32399'
down_revision: Union[str, Sequence[str], None] = 'ccd4c83d1f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('services', sa.String(length=255), nullable=True))
    op.drop_column('messages', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('messages', 'services')
    # ### end Alembic commands ###
